### ISSUE TITLE
Unable to build tink-rust binaries

### ISSUE THREAD

**Issue by dnovick** [project-oak/tink-rust#128]
While trying to do a cargo build on tink-rust, I'm receiving the following error blurb, 

"Compiling tink-testing-server v0.1.0 (/home/dnovick/gitrepos/rust/tink-rust/testing)
error: failed to run custom build command for `tink-testing-server v0.1.0 (/home/dnovick/gitrepos/rust/tink-rust/testing)`

Caused by:
  process didn't exit successfully: `/home/dnovick/gitrepos/rust/tink-rust/target/debug/build/tink-testing-server-861acf93ba28d1bf/build-script-build` (exit code: 1)
  --- stdout
  cargo:rerun-if-changed=proto/testing_api.proto

  --- stderr
  error: no override and no default toolchain set".

Unfortunately, I don't see enough info in the error to clue me in on exactly what is wrong. I'm building on an Ubuntu 20.04. I made sure I pulled the Wycheproof submodule. Are there other build tools or settings I'm unaware of? Note: the lib builds fine. This error only occurs when trying to build the binaries.

Thanks,
Dave

**Comment by daviddrysdale** [comment]
I'd *guess* it's `protoc`-related:
- The "normal" crates (specifically `tink-proto`) have a `build-dependency` on `prost-build`, used to translate `.proto` message definitions into Rust structure definitions.
- The `tink-testing` crate instead has a `build-dependency` on `tonic-build`, in order to translate `.proto` message *and service* definitions into Rust structures and traits, using `prost` under the covers.

Could you see whether anything in the [text about finding `protoc`](https://docs.rs/prost-build/0.7.0/prost_build/#sourcing-protoc)  (or in `env | grep PROTO`) that might be relevant to your local environment?

**Comment by dnovick** [comment]
I figured out the problem. I am new to Rust and its dev environment. I had received errors when trying to install other tools about not having a Rust toolchain installed. I wasn't sure what this was about, and looked into it. Apparently, when I installed, I didn't install an associated toolchain. Once I did that, the Tink build completed successfully. Thanks for the help.

**Comment by daviddrysdale** [comment]
Thanks for the update, glad you've sorted it out.
