### ISSUE TITLE
Publish crates to crates.io

### ISSUE THREAD

**Issue by daviddrysdale** [project-oak/tink-rust#32]

**Comment by daviddrysdale** [comment]
There is already a (vestigial) [tink](https://crates.io/crates/tink) crate, so will probably need to rename our `tink` crate to (e.g.) `tink-core`

**Comment by str4d** [comment]
It looks like the `tink` crate is https://github.com/jakeswenson/rust-tink. @jakeswenson maybe you'd like to collaborate here?

**Comment by jakeswenson** [comment]
I'd love to help out here! Do you have an automated build setup already?
I should have made @daviddrysdale a co-owner on the `tink` crate.

**Comment by daviddrysdale** [comment]
> I'd love to help out here! 

Thanks, much appreciated!

> Do you have an automated build setup already?

There are [Github Actions](https://github.com/project-oak/tink-rust/actions) for:
 - [CI](https://github.com/project-oak/tink-rust/blob/main/.github/workflows/ci.yml): build/test/clippy/rustfmt/doc/coverage (runs on PRs and pushes)
 - [crosstest](https://github.com/project-oak/tink-rust/blob/main/.github/workflows/crosstest.yml): cross-language (C++/Java/Python/Go/Rust) tests against upstream Tink code (just runs on pushes to `main`, as it's time-consuming)

But if you can think of other things to check/build/test, that would be great.

> co-owner on the tink crate.

Is it allowable/acceptable for this project to take over the `tink` crate name?

(If not, I can rename that particular crate &ndash; there's already a bunch of pending [inter-crate reorganization](https://github.com/project-oak/tink-rust/pull/64) that's needed to make things crates.io-ready)

**Comment by jakeswenson** [comment]
Love it. I have forked this repository and will begin working on this.

> Is it allowable/acceptable for this project to take over the tink crate name?
> 
> (If not, I can rename that particular crate – there's already a bunch of pending inter-crate reorganization that's needed to make things crates.io-ready)

**No issues from my side.** I created an empty library with `0.0.0` as a version to reserve the crate name. I see no issues with this project/library being the proper publisher of this crate. 

Before I begin I wanted to discuss what you all would like the release process to be. 
Do you all already have a process in place to perform releases? Or an existing plan in place or documentation?

If not, I have something for another project of mine, which I can use as a starter.
It relies on [`cargo-release`](https://github.com/sunng87/cargo-release) which means there is a manual step to kick off the release process. 
[Here](https://github.com/jakeswenson/otpcli/blob/master/.github/workflows/release.yaml) is the workflow for it.
At a high level the steps are as follows:
1. _Manually_ run `cargo release [type]`. 
  This:
    - Creates a git tag with the version being released
    - Updates the version in the cargo.toml files to be a `-alpha` patch
2. Since a new tag was created it will trigger the release workflow in GitHub Actions.
3. The first step in this workflow is to create a **draft** GitHub release for that newly created release version tag.
  As a part of this draft release process, I use an action to produce a changelog in the release body of all of the commits since the last release.
    > In the longer term, I'd rather move to [semantic commit messages](https://nitayneeman.com/posts/understanding-semantic-commit-messages-using-git-and-angular/) a la [angular commit messages](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y).
4. This GA workflow will then build for my build matrix so that binaries can be uploaded and attached to the GitHub release.
    > _not needed here since this is a library only_
5. Once a successful build happens the build will be published to `crates.io`
6. *Manually* go to the release and publish it (since it is a draft release.)

Thoughts on this process @daviddrysdale @str4d?

For now, I will work on this in my fork and publish it to a temporary crate that I will remove later...

**Comment by daviddrysdale** [comment]
> Before I begin I wanted to discuss what you all would like the release process to be.
Do you all already have a process in place to perform releases? Or an existing plan in place or documentation?

Up to now, this has mostly been a development repo, and it turns out that some of the directory/crate structure probably needs rejigging before we can think about releasing.

The reorganisation work is in progress in #64, but the key points are:
 - The `proto/` directory needs to live inside a specific crate, so `build.rs` runs are self-contained. #64 makes that location a new `tink-proto` crate (because it's useful in other contexts to have those protobuf message definitions available separately).
 - All of the integration tests for the different crates get pulled out into a separate `tink-tests` crate, because of two problems with releasing:
   -  It's a lot of code to ship along with a library.  I guess that could be solved with an `exclude` stanza in `Cargo.toml`, but that doesn't help with&hellip;
   -  There are circular `dev-dependencies` between the crates (e.g. integration tests for `tink` dev-depend on `tink-mac`, which depends on `tink`).

(I'm very open to alternative suggestions if there are better solutions for these problems, BTW)

That leaves a set of crates with acyclic dependencies that could (I think!) be released in order (`tink`, `tink-prf`,`tink-mac`, `tink-aead`, `tink-streaming-aead` `tink-daead`, `tink-signature`, `tink-awskms`, `rinkey`), plus a couple of test-only crates (`tink-tests`, `tink-testing-server`) that don't get released.

> It relies on cargo-release 

`cargo-release` sounds like a more comprehensive tool than the [shell scripts](https://github.com/project-oak/tink-rust/pull/64/files?file-filters%5B%5D=.sh#diff-1bba00e5aca52286a667c09eff92ba2ca8e3ca77e0d31b0599cc829ab0173389) I started putting together in #64, but does it cope with multi-crate repos? 

In particular, if I understand the crates.io constraints correctly (a big if), I don't think it's possible to package up (say) `tink-prf` v0.1.0 until `tink` v0.1.0 (on which it depends) has been published at crates.io.

> Thoughts on this process @daviddrysdale @str4d?

Nice, thanks &ndash; it sounds pretty similar to the more-manual process I was planning to experiment with:

 - Run something like `scripts/rev-up.sh 0.3.0 0.3` which:
   - Makes all crate versions `0.3.0`
   - Makes all inter-crate dependencies `^0.3`
   - Adds a `v0.3.0` Git tag
 - Push the commit to Github as a temporary branch (i.e. deliberately **not** making the Git tag visible yet),  and check that the [CI](https://github.com/project-oak/tink-rust/actions?query=workflow%3ACI) and [crosstest](https://github.com/project-oak/tink-rust/actions?query=workflow%3Acrosstest) actions are green
 - Make the release public:
   - Push the new tag to GitHub
   - Make a GitHub release off of the tag
   - Run something like `scripts/release.sh` to release the crates to crates.io in dependency order.

(As time goes on and the wrinkles are ironed out, I'd imagine a lot of those steps would shift from being manual to being automatic, as you suggest.)

**Comment by daviddrysdale** [comment]
> > Is it allowable/acceptable for this project to take over the tink crate name?
>
> No issues from my side. I created an empty library with 0.0.0 as a version to reserve the crate name. I see no issues with this project/library being the proper publisher of this crate.

Hi @jakeswenson, I think we're just about ready to do a release to crates.io (after #64 and #75) &ndash; are you still willing & able to relinquish https://crates.io/crates/tink ? Thanks!

**Comment by daviddrysdale** [comment]
> are you still willing & able to relinquish https://crates.io/crates/tink ?

@jakeswenson : My apologies, I messed up &ndash; you helpfully sent an ownership invite for `tink` and I didn't see it (because I hadn't fully configured my crates.io account).  So I went ahead and unnecessarily renamed (#77) the `tink` crate here to `tink-core` and [released](https://crates.io/crates/tink-core) under that name.
